### ISSUE TITLE
Unable to launch launcher v1.6

### ISSUE THREAD

**Issue by GlitchingCloud** [POE-Addon-Launcher/PoE-Addon-Launcher#17]
Here's the backtrace:

> E:\PAl\PoE_Addon_Launcher.jar
> сен 28, 2018 9:20:54 PM javafx.fxml.FXMLLoader$ValueElement processValue
> WARNING: Loading FXML document with JavaFX API of version 10.0.1 by JavaFX runtime of version 8.0.181
> Attempting to read core_settings.pal
> Connecting to GitHub anonymously
> Exception in thread "Thread-5" java.lang.NullPointerException
>         at GUI.LauncherUI_Controller.lambda$daemon_checker$6(LauncherUI_Controller.java:276)
>         at java.lang.Thread.run(Unknown Source)

**Comment by POE-Addon-Launcher** [comment]
@GlitchingCloud  can you try this launcher to see if this fixes it?
[PoE-Addon-Manager-Launcher-1.6-jar-with-dependencies.jar.zip](https://github.com/POE-Addon-Launcher/PoE-Addon-Launcher/files/2436933/PoE-Addon-Manager-Launcher-1.6-jar-with-dependencies.jar.zip)
